server:
  port: 8080

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/semilleros
    username: root
    password: 1152069
  jpa:
    show-sql: true
    hibernate:
      ddl-auto:  create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect